version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: dev-tools-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: dev-tools-mongo
      ME_CONFIG_BASICAUTH_USERNAME: vfcarmo
      ME_CONFIG_BASICAUTH_PASSWORD: MongoDB@2021
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB@2021
    links:
      - mongo-db
    networks:
      - dev-tools-mongo-network

  mongo-db:
    image: mongo
    container_name: dev-tools-mongo
    environment:
      MONGO_INITDB_DATABASE: demodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB@2021
    ports:
      - "27017:27017"
    volumes:
      - ~/Dev/Docker-Compose/MongoDB:/data/db
    networks:
      - dev-tools-mongo-network

networks: 
    dev-tools-mongo-network:
      driver: bridge